name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: jasmineapp

    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: jasmineapp/package-lock.json

      - run: npm ci

      - name: Build Angular
        run: |
          npm run build -- \
          --configuration production \
          --base-href /Jasmine/

      - name: Routing fix
        run: cp dist/jasmineapp/browser/index.html dist/jasmineapp/browser/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: jasmineapp/dist/jasmineapp/browser

      - name: Deploy
        uses: actions/deploy-pages@v4