name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: jasmineapp

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: jasmineapp/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: |
          npm run build -- \
          --configuration production \
          --base-href /Jasmine/
          
      - name: Routing fix for Angular on GitHub Pages
        run: cp dist/jasmineapp/index.html dist/jasmineapp/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: jasmineapp/dist/jasmineapp

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4